### PR TITLE
Extended mutators check

### PR DESCRIPTION
**Pull request by askmatey**
asciidisco/Backbone.Mutators#34

### CODE REVIEW

**Comment by asciidisco** [comment]
I´m totally out of the Backbone game for some time know, but the change looks good, so I´m pulling it in & I´m going to release a new version.

**Comment by cluebcke** [comment]
Hi Sebastian - think we had this conversation a while ago, but if you're looking for someone to take over maintainence of this project, I'd be happy to. I use Mutators every day (well that and a fork I made that combines its functionality with DeepModel), and I forsee using it for a long time to come.

**Comment by asciidisco** [comment]
@cluebcke Thanks for the help, that is very appreciated :)
I already added you as a collaborator on gh, can you also tell me your npm username, so that I can add you there as well, so that you are able to publish the package?

**Comment by cluebcke** [comment]
Cool! npm username is also cluebcke

**Pull request merged**
